export const routes = {
  home: "/",
  events: "/eventos",
  event: (slug: string) => `/eventos/${slug}`,
  eventPhoto: (slug: string, photoId: string) => `/eventos/${slug}/${photoId}`,
  qr: (code: string) => `/e/${code}`,
  qrGeneral: "/e",
  login: "/login",
  register: "/register",
  photographer: {
    dashboard: "/fotografo",
    events: "/fotografo/eventos",
    newEvent: "/fotografo/eventos/nuevo",
    event: (id: string) => `/fotografo/eventos/${id}`,
    requests: "/fotografo/solicitudes",
    profile: "/fotografo/perfil",
    settings: "/fotografo/ajustes",
    onboarding: "/fotografo/onboarding",
  },
  client: {
    dashboard: "/cliente",
    favorites: "/cliente/favoritos",
    requests: "/cliente/solicitudes",
    profile: "/cliente/perfil",
  },
  admin: {
    dashboard: "/admin",
    users: "/admin/usuarios",
    events: "/admin/eventos",
    requests: "/admin/solicitudes",
    qr: "/admin/qr",
    config: "/admin/configuracion",
  },
  legal: {
    hub: "/legales",
    document: (slug: string) => `/legales/${slug}`,
    terms: "/legales/terminos-y-condiciones",
    privacy: "/legales/privacidad",
    cookies: "/legales/cookies",
    notice: "/legales/aviso-legal",
    intellectualProperty: "/legales/propiedad-intelectual",
    consumers: "/legales/defensa-del-consumidor",
  },
} as const;
